add_newline = true
format = '$all$fill$time$line_break$jobs$battery$status$os$container$netns$shell$character'

[username]
show_always = true
style_user = "bold green"
style_root = "bold red"

[directory]
truncate_to_repo = false

[time]
disabled = false
format = "[$time]($style) "
time_format = "%H:%M"
